# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: default

channels:
  - conda-forge

dependencies:
  - python
  - click
  - grayskull
  - jinja2
  - pygithub
  - pyyaml
  - requests
